build:
    image: default-bionic
    services:
        mysql: 8.0.29
    environment:
        php:
            version: 8.3.21
            ini:
                xdebug.mode: coverage
        node: false
        postgresql: false
        mongodb: false
        elasticsearch: false
        redis: false
        memcached: false
        neo4j: false
        rabbitmq: false
        variables:
            APP_ENV: 'scrutinizer'
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
    dependencies:
        before:
            - composer self-update
            - mysql -u root -e "CREATE DATABASE IF NOT EXISTS slim_skeleton_test CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
    tests:
        before:
            -   command: composer test:coverage
                coverage:
                    file: 'build/coverage/clover.xml'
                    format: 'clover'
